# Generated by Django 3.1.6 on 2021-02-24 17:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=10, unique=True)),
                ('balance', models.IntegerField(default=1000)),
                ('account_pin', models.IntegerField(unique=True)),
                ('date_opened', models.DateField(default=datetime.datetime(2021, 2, 24, 9, 52, 24, 707562))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('Place', models.CharField(default='', max_length=100)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(max_length=100, verbose_name='account no')),
                ('account_pin', models.IntegerField()),
                ('amount', models.IntegerField(default=100)),
                ('transfer_date_time', models.DateTimeField(default=datetime.datetime(2021, 2, 24, 9, 52, 24, 708562), verbose_name='date and time')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.accountinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_pin', models.IntegerField()),
                ('amount', models.IntegerField(default=100)),
                ('type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], default='deposit', max_length=100)),
                ('transaction_date_time', models.DateTimeField(default=datetime.datetime(2021, 2, 24, 9, 52, 24, 708562), verbose_name='date and time')),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.accountinfo')),
            ],
        ),
    ]
