# Generated by Django 3.1.4 on 2021-02-22 23:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=10, unique=True)),
                ('balance', models.IntegerField(default=1000)),
                ('account_pin', models.IntegerField(unique=True)),
                ('date_opened', models.DateTimeField(default=datetime.date(2021, 2, 22))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('Place', models.CharField(default='', max_length=100)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_pin', models.IntegerField()),
                ('amount', models.IntegerField(default=100)),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw')], default='deposit', max_length=100)),
                ('transaction_date', models.DateTimeField(default=datetime.date(2021, 2, 22), verbose_name='date')),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.accountinfo')),
            ],
        ),
    ]
