# Generated by Django 3.1.6 on 2021-02-24 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='account_pin',
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='date_opened',
            field=models.DateField(default=datetime.datetime(2021, 2, 24, 9, 58, 49, 404007)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 9, 58, 49, 405005), verbose_name='date and time'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 9, 58, 49, 406008), verbose_name='date and time'),
        ),
    ]
