# Generated by Django 3.1.6 on 2021-02-23 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210222_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='date_opened',
            field=models.DateField(default=datetime.datetime(2021, 2, 23, 9, 50, 55, 285144)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date_time',
            field=models.DateField(default=datetime.datetime(2021, 2, 23, 9, 50, 55, 285144), verbose_name='date and time'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date_time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 23, 9, 50, 55, 286142), verbose_name='date and time'),
        ),
    ]
